ColorColumn: '- shadow'
Conceal: ''
Cursor: ''
CursorIM: ''
CursorColumn: '- shadow'
CursorLine: '- shadow'
CursorLineNr: 'blue2 - '
Directory: 'blue1 -'
DiffAdd: '- grey5'
DiffChange: '- bg'
DiffDelete: 'red1 red3'
DiffText: '- yellow1 r'
ErrorMsg: 'red1 - r'
VertSplit: 'bg bg'
Folded: 'grey2 dark'
FoldColumn: 'grey2 dark'
SignColumn: 'grey1 bg'
IncSearch: 'highlighted darkest br'
LineNr: 'grey3 -'
MatchParen: 'red1 - b'
ModeMsg: ''
MoreMsg: ''
NonText: 'grey3 -'
Normal: 'text bg'
PMenu: 'pearl darkest'
PMenuSel: 'blue4 shadow'
PmenuSbar: 'blue4 blue4'
PmenuThumb: 'green1 green1'
Question: 'green1 -'
Search: 'highlighted - ub'
SpecialKey: 'grey3 -'
SpellBad: 'red1'
SpellLocal: 'yellow1'
SpellCap: 'yellow2'
SpellRare: 'blue2'
StatusLine: 'darker grey2 b'
StatusLineNC: 'grey1 grey3'
TabLine: 'grey1 grey3'
TabLineFill: '- grey3'
TabLineSel: 'green1 - b'
Title: 'blue1 - b'
Visual: '- blue5 b'
VisualNOS: '- blue5 b'
WarningMsg: 'red1 -'
WildMenu: 'bg green1 b'
Comment: 'grey2'
Constant: 'yellow2 -'
String: 'green1 -' # Constant
Character: 'yellow2 -' # Constant
Boolean: 'yellow2 -' # Constant
Number: 'yellow2 -' # Constant
Float: 'yellow2 -' # Constant
Identifier: 'blue4 -'
Function: 'blue4' # Identifier
Statement: 'blue1 -'
Conditional: 'green1 -' # Statement
Repeat: 'blue2' # Statement
Label: '' # Statement
Operator: 'red1 -' # Statement
Keyword: '' # Statement
Exception: 'red1 -' # Statement
PreProc: 'green1 -'
Include: 'blue2' # PreProc
Define: '' # PreProc
Macro: '' # PreProc
PreCondit: '' # PreProc
Type: 'yellow1 - '
StorageClass: 'pink2' # Type
Structure: '' # Type
Typedef: '' # Type
Special: 'blue2 -'
SpecialChar: '' # Special
Tag: '' # Special
Delimiter: '' # Special
SpecialComment: '' # Special
Debug: '' # Special
Underlined: '- - u'
Ignore: ''
Error: 'text red1'
Todo: 'red1 - b'
